Enum / IT-Academy / JC1-117-22-dev / Haretski Aliaksei / Task01-07
rakovets/course-java-core pull request #1005
Opened 2022-10-12 15:13 UTC by haretski-aliaksei

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-10-12 15:16 UTC, haretski-aliaksei commented
Previous PR I put in incorrect section of "Rakovets Lab" (lesson09 < lesson10):
https://github.com/rakovets/course-java-core/pull/986

2022-11-28 02:35 UTC, rakovets requested changes
need to fix

2022-11-28 02:35 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/enum_types/Task01040506Seasons.java
> +        }
move to enum, not INSTANCE

2022-11-28 02:35 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/enum_types/Task01040506Seasons.java
> +public enum Task01040506Seasons {
```suggestion
public enum Season {
```

2022-11-28 02:35 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/enum_types/Task01040506Seasons.java
> +    private double averageTemperaturePerSeason;
```suggestion
    private final double averageTemperaturePerSeason;
```

2022-11-28 02:35 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/enum_types/Task01040506Seasons.java
> +    public double getAverageTemperaturePerSeason(Task01040506Seasons season) {
```suggestion
    public double getAverageTemperature(Task01040506Seasons season) {
```

2022-11-28 02:35 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/enum_types/Task03SeasonsSwitch.java
> +public class Task03SeasonsSwitch {
move to `test`

2022-11-28 02:35 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/enum_types/Task07Print.java
> +public class Task07Print {
move to `test`

2022-11-28 02:35 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/enum_types/Task02PrintEnum.java
> +public class Task02PrintEnum {
move to `test`

2022-11-28 02:35 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/enum_types/TestEnum.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2023-02-19 09:46 UTC, closed without merging