Exception Handling / IT-Academy / JC1-117-22-dev / Haretski Aliaksei / Done tasks 01-07
rakovets/course-java-core pull request #1012
Opened 2022-10-14 14:38 UTC by haretski-aliaksei

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-10-17 03:49 UTC, rakovets requested changes
You need to fix and add correct solutions

2022-10-17 03:49 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/exception/ExceptionTask06CollarIsPutOn.java
> +public class ExceptionTask06CollarIsPutOn extends RuntimeException{
```suggestion
public class ExceptionTask06CollarIsPutOn extends RuntimeException {
```

2022-10-17 03:49 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task03Demo.java
> +            logger.info(exception.getMessage());
wrong solution

2022-10-17 03:49 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task04Demo.java
> +            logger.info(exception.getMessage());
wrong solution

2022-10-17 03:49 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task06Dog.java
> +    String name;
```suggestion
    private String name;
```

2022-10-17 03:49 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task06Demo.java
> +            exception.printStackTrace();
printStackTrace...
Where?

2022-10-18 17:13 UTC, haretski-aliaksei commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/exception/ExceptionTask06CollarIsPutOn.java
> +public class ExceptionTask06CollarIsPutOn extends RuntimeException{
fixed

2022-10-18 17:20 UTC, haretski-aliaksei commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task03Demo.java
> +            logger.info(exception.getMessage());
fixed

2022-10-18 17:27 UTC, haretski-aliaksei commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task06Dog.java
> +    String name;
fixed

2022-10-18 17:28 UTC, haretski-aliaksei commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task06Demo.java
> +            exception.printStackTrace();
fixed

2022-10-18 17:33 UTC, closed without merging

2022-10-18 17:38 UTC, haretski-aliaksei commented
Fixed PR: https://github.com/rakovets/course-java-core/pull/1032