exception_handling/ it-academy.by/ JC1-117-22/Kavaliova Hanna/Done all tasks
rakovets/course-java-core pull request #1018
Opened 2022-10-16 11:15 UTC by Hanna1201

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-10-17 04:00 UTC, rakovets requested changes
You need use logger

2022-10-17 04:05 UTC, rakovets requested changes
You need to fix and add correct solutions

2022-10-17 04:05 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task03Demo.java
> +            e.printStackTrace();
use logger and stacktrace

2022-10-17 04:05 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task04.java
> +    public int numberIsNegativeException(int number) throws NegativeNumberException {
```suggestion
    public int numberIsNegativeException(int number) {
```

2022-10-17 04:05 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task03Demo.java
> +            e.printStackTrace();
wrong solution

2022-10-17 04:05 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task04Demo.java
> +            e.printStackTrace();
wrong solution

2022-10-17 04:05 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task05.java
> +    public int divisionTwoNumber(int firstNumber, int secondNumber) throws DivisionTwoNumbersExcepton {
```suggestion
    public int divisionTwoNumber(int firstNumber, int secondNumber) {
```

2022-11-01 16:06 UTC, Hanna1201 commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task05.java
> +    public int divisionTwoNumber(int firstNumber, int secondNumber) throws DivisionTwoNumbersExcepton {
fixed

2022-11-01 16:06 UTC, Hanna1201 commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task04.java
> +    public int numberIsNegativeException(int number) throws NegativeNumberException {
fixed

2023-01-30 13:59 UTC, rakovets commented
outdated

2023-01-30 13:59 UTC, closed without merging