exception_handling / it-academy / JC1-117-22 / Victor Polonnikov / Done tasks 1-7
rakovets/course-java-core pull request #1020
Opened 2022-10-16 12:41 UTC by VictPol

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-10-19 03:10 UTC, rakovets requested changes
You need to fix and add correct solution

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/JavaUtilLogging02.java
> +public class JavaUtilLogging02 {
remove it

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/JavaUtilLogging01.java
> +public class JavaUtilLogging01 {
remove it

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Demo01.java
> +            Logger logger = Logger.getLogger(JavaUtilLogging01.class.getName());
Use logger for current class

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Demo01.java
> +        } catch (Exception e) {
catch `NullPointerException`

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Demo02.java
> +            System.out.printf("сумма первых %d чисел массива составляет %d", num, sum);
remove it from prod code

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task03.java
> +    final int MINIMUM_ACCOUNT_AMOUNT = 100;
```suggestion
    private final int MINIMUM_TERM_AFTER_OPEN_ACCOUNT = 2;
    private final int MINIMUM_ACCOUNT_AMOUNT = 100;
```

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/exceptions/MyExceptionTask03.java
> +        public MyExceptionTask03(String message, String debugMessage) {
remove not use code

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Demo03.java
> +        System.out.printf("Остаток на счете после снятия с составляет: %d", restOfAccountAfterRequest);
remove it form prod code

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Demo03.java
> +            logger.warning(e.getDebugMessage());
Where is stacktrace?

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task04.java
> +
remove it
default value for int: 0

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task04.java
> +    public void openAccount(int amountToOpenAccount, int ageOfClient) throws MyExceptionTask04 {
```suggestion
    public void openAccount(int amountToOpenAccount, int ageOfClient) {
```

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/exceptions/MyExceptionTask04.java
> +    }
remove unused code

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Demo04.java
> +            logger.warning(e.toString());
Where is stacktrace?

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task07.java
> +    public static void printArray(int sizeOfArray, int startToPrintArray, int endToPrintArray, final int MAXIMUM_SIZE_OF_ARRAY) throws MyExeptionTask07{
```suggestion
    private final int MAXIMUM_SIZE_OF_ARRAY = 10;
    
    public static void printArray(int sizeOfArray, int startToPrintArray, int endToPrintArray, final int MAXIMUM_SIZE_OF_ARRAY) throws MyExeptionTask07{
```

2022-10-19 03:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task07.java
> +    public static void printArray(int sizeOfArray, int startToPrintArray, int endToPrintArray, final int MAXIMUM_SIZE_OF_ARRAY) throws MyExeptionTask07{
```suggestion
    public void printArray(int sizeOfArray, int startToPrintArray, int endToPrintArray, final int MAXIMUM_SIZE_OF_ARRAY) throws MyExeptionTask07{
```

2022-10-28 11:15 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Demo02.java
> +            Logger logger = Logger.getLogger(JavaUtilLogging02.class.getName());
fixed

2022-10-28 11:16 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/JavaUtilLogging02.java
> +public class JavaUtilLogging02 {
fixed

2022-10-28 11:19 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/JavaUtilLogging01.java
> +public class JavaUtilLogging01 {
fixed

2022-10-28 11:22 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Demo01.java
> +        } catch (Exception e) {
fixed

2022-10-28 11:23 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Demo02.java
> +            System.out.printf("сумма первых %d чисел массива составляет %d", num, sum);
fixed

2022-10-28 11:24 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task03.java
> +    final int MINIMUM_ACCOUNT_AMOUNT = 100;
fixed

2022-10-28 11:35 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/exceptions/MyExceptionTask03.java
> +        public MyExceptionTask03(String message, String debugMessage) {
fixed

2022-10-28 11:35 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Demo03.java
> +        System.out.printf("Остаток на счете после снятия с составляет: %d", restOfAccountAfterRequest);
fixed

2022-10-28 11:37 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task04.java
> +
fixed

2022-10-28 11:38 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task04.java
> +    public void openAccount(int amountToOpenAccount, int ageOfClient) throws MyExceptionTask04 {
fixed

2022-10-28 11:40 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/exceptions/MyExceptionTask04.java
> +    }
fixed

2022-10-28 11:41 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Demo04.java
> +            logger.warning(e.toString());
fixed

2022-10-28 11:41 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task07.java
> +    public static void printArray(int sizeOfArray, int startToPrintArray, int endToPrintArray, final int MAXIMUM_SIZE_OF_ARRAY) throws MyExeptionTask07{
fixed

2022-10-28 11:46 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task07.java
> +    public static void printArray(int sizeOfArray, int startToPrintArray, int endToPrintArray, final int MAXIMUM_SIZE_OF_ARRAY) throws MyExeptionTask07{
fixed

2023-01-30 13:59 UTC, rakovets commented
outdated

2023-01-30 13:59 UTC, closed without merging