exception_handling / it-academy.by / JC1-117-22 / Aliaksei Kharko / Done tasks 01-07
rakovets/course-java-core pull request #1022
Opened 2022-10-16 13:23 UTC by KharkoAO

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-10-19 03:16 UTC, rakovets requested changes
You need fix and add correct solutions

2022-10-19 03:16 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/JavaUtilLogging/JavaUtilLogging.java
> +public class JavaUtilLogging {
remove it

2022-10-19 03:16 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task01Demo.java
> +public class Task01Demo {
add logger for each class

2022-10-19 03:16 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task04.java
> +    public int calculatorDividing(int dividend, int divisor) throws ZeroCheckException {
```suggestion
    public int calculatorDividing(int dividend, int divisor) {
```

2022-10-19 03:16 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task04Demo.java
> +            ex.printStackTrace();
use logger for stacktrace

2022-10-19 03:16 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task03Demo.java
> +            logger.severe(ex.getMessage());
where is stacktrace?

2022-10-19 03:16 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task06Demo.java
> +        }
wrong solution

2022-11-25 14:26 UTC, KharkoAO commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/JavaUtilLogging/JavaUtilLogging.java
> +public class JavaUtilLogging {
this fixed

2022-11-25 14:26 UTC, KharkoAO commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task01Demo.java
> +public class Task01Demo {
this fixed

2022-11-25 14:26 UTC, KharkoAO commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task04Demo.java
> +            ex.printStackTrace();
this fixed

2022-11-25 14:26 UTC, KharkoAO commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task03Demo.java
> +            logger.severe(ex.getMessage());
this fixed

2022-11-25 14:26 UTC, KharkoAO commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task06Demo.java
> +        }
this fixed

2023-01-30 13:57 UTC, rakovets commented
outdated

2023-01-30 13:57 UTC, closed without merging