lambda_expressions / it-academy.by / JC1-117-22 / Aliaksei Kharko / Done tasks and tests
rakovets/course-java-core pull request #1067
Opened 2022-10-31 15:15 UTC by KharkoAO

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-11-02 04:08 UTC, rakovets requested changes
need to fix

2022-11-02 04:08 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/Task01.java
> +                .flatMap(m -> Stream.of(m.getKey(), m.getValue())).toArray(String[]::new);
```suggestion
                .flatMap(m -> Stream.of(m.getKey(), m.getValue()))
                .toArray(String[]::new);
```

2022-11-02 04:08 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/Task01Demo.java
> +    }
please write tests

2022-11-02 04:08 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/maths_statistics/MathsStatistics.java
> +    public List<Integer> creationSetRandomNumbers() {
bad API

2022-11-02 04:08 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/maths_statistics/MathsStatistics.java
> +                .filter(x -> x % 2 == 0).count();
```suggestion
                .filter(x -> x % 2 == 0)
                .count();
```

2022-11-02 04:08 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/maths_statistics/MathsStatistics.java
> +                .filter(x -> x % 2 != 0).count();
alike

2022-11-02 04:08 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/maths_statistics/MathsStatistics.java
> +                .filter(x -> x == 0).count();
alike

2022-11-02 04:08 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/maths_statistics/MathsStatistics.java
> +                .filter(x -> x == number).count();
alike

2022-11-02 04:08 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/tv/InformationSystemTv.java
> +    }
Where do you use this field?

2022-11-02 04:08 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/city_helter/CityHelper.java
> +    public List<String> getCityNamesGivenLength(List<String> listCities) {
bad API

2022-11-02 04:08 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/CityHelperTest.java
> +    CityHelper city = new CityHelper();
use `@BeforeAll`

2022-11-02 04:08 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/MathStatisticDemo.java
> +    }
please, write tests

2022-11-04 17:55 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/Task01.java
> +                .flatMap(m -> Stream.of(m.getKey(), m.getValue())).toArray(String[]::new);
This fixed

2022-11-04 17:55 UTC, KharkoAO commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/Task01Demo.java
> +    }
Done

2022-11-04 17:55 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/maths_statistics/MathsStatistics.java
> +    public List<Integer> creationSetRandomNumbers() {
This fixed

2022-11-04 17:56 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/maths_statistics/MathsStatistics.java
> +                .filter(x -> x % 2 == 0).count();
This fixed

2022-11-04 17:56 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/maths_statistics/MathsStatistics.java
> +                .filter(x -> x % 2 != 0).count();
This fixed

2022-11-04 17:56 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/maths_statistics/MathsStatistics.java
> +                .filter(x -> x == 0).count();
This fixed

2022-11-04 17:57 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/maths_statistics/MathsStatistics.java
> +                .filter(x -> x == number).count();
This fixed

2022-11-04 17:57 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/tv/InformationSystemTv.java
> +    }
This fixed

2022-11-04 17:57 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/city_helter/CityHelper.java
> +    public List<String> getCityNamesGivenLength(List<String> listCities) {
This fixed

2022-11-04 17:57 UTC, KharkoAO commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/MathStatisticDemo.java
> +    }
Done

2023-02-19 09:47 UTC, closed without merging