concurrency / it-academy / JC-117-22 / Victor Polonnikov / Done tasks of 2 projects
rakovets/course-java-core pull request #1084
Opened 2022-11-07 00:36 UTC by VictPol

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-11-09 04:13 UTC, rakovets requested changes
Not correct project 'Producer Queue Consumer'

You need create classes:
- Consumer
- Producer
- Container with Queue

Demo class ISN'T source code! move to test!

2022-11-09 04:13 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/backup_utility/BackupUtility.java
> +}
where is concurrency?

2022-11-12 13:30 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/backup_utility/BackupUtility.java
> +}
fixed

2022-11-12 13:33 UTC, VictPol commented
All fixed

2023-02-19 09:47 UTC, closed without merging