concurrency / it-academy.by / JC1-117-22 / Aliaksei Kharko / Done tasks and demo
rakovets/course-java-core pull request #1089
Opened 2022-11-08 22:44 UTC by KharkoAO

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-11-09 04:30 UTC, rakovets requested changes
need to fix and add solution for Backup utility

2022-11-09 04:30 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/producer_queue_consumer/exception/UserInputException.java
> +public class UserInputException extends Exception{
```suggestion
public class UserInputException extends Exception {
```

2022-11-09 04:30 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/producer_queue_consumer/Report.txt
> +2022-11-09 01:17:21.091 - Consumer 3 - I slept 2 seconds
remove it

2022-11-09 04:30 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/producer_queue_consumer/Producer.java
> +                input = scanner.nextLine();
use `nextInt()`

2022-11-09 04:30 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/producer_queue_consumer/Consumer.java
> +                    new FileWriter("D://JavaProjects/course-java-core" +
hardcode

2022-11-09 04:30 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/producer_queue_consumer/Consumer.java
> +        } catch (IOException | InterruptedException | NullPointerException e) {
NPE?

2022-11-09 04:30 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/producer_queue_consumer/Consumer.java
> +    private final int MILLS_IN_SECOND = 1000;
```suggestion
    private final int MILLS_IN_SECOND = 1000;
    
    private Timestamp timestamp = new Timestamp(System.currentTimeMillis());
    private QueueNumbersFromStream queue;

```

2022-11-22 14:16 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/producer_queue_consumer/exception/UserInputException.java
> +public class UserInputException extends Exception{
this fixed

2022-11-22 14:16 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/producer_queue_consumer/Report.txt
> +2022-11-09 01:17:21.091 - Consumer 3 - I slept 2 seconds
this fixed

2022-11-22 14:16 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/producer_queue_consumer/Producer.java
> +                input = scanner.nextLine();
this fixed

2022-11-22 14:17 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/producer_queue_consumer/Consumer.java
> +                    new FileWriter("D://JavaProjects/course-java-core" +
this fixed

2022-11-22 14:17 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/producer_queue_consumer/Consumer.java
> +        } catch (IOException | InterruptedException | NullPointerException e) {
this fixed

2022-11-22 14:19 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/producer_queue_consumer/Consumer.java
> +    private final int MILLS_IN_SECOND = 1000;
this fixed

2023-02-19 09:48 UTC, closed without merging