Reflection / IT-Academy / JC1-117-22-dev / Haretski Aliaksei / Done all tasks
rakovets/course-java-core pull request #1103
Opened 2022-11-20 18:28 UTC by haretski-aliaksei

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-11-21 15:19 UTC, rakovets requested changes
Where is tests OR demo?

2022-11-21 15:19 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/reflection/reflection_utils/ReflectionUtils.java
> +     * @return "Field"
Use `@see`

2022-11-21 15:19 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/reflection/reflection_utils/ReflectionUtils.java
> +    public Field getFieldFromName(Class className, String fieldName) {
```suggestion
    public Field getFieldByName(Class clazz, String fieldName) {
```

2022-11-21 15:19 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/reflection/reflection_utils/ReflectionUtils.java
> +            throw new RuntimeException(e);
use Reflection API exceptions OR throw custom exception

2022-11-24 15:20 UTC, haretski-aliaksei commented on src/main/java/com/rakovets/course/java/core/practice/reflection/reflection_utils/ReflectionUtils.java
> +    public Field getFieldFromName(Class className, String fieldName) {
Fixed

2022-11-25 09:04 UTC, closed without merging

2022-11-25 09:08 UTC, haretski-aliaksei commented
Fixed PR: https://github.com/rakovets/course-java-core/pull/1117