Conditional statements/ it-academy.by / M-JC1-66-20 / Anton Khramau / Done Task 1-14
rakovets/course-java-core pull request #270
Opened 2021-01-01 20:03 UTC by Igrok023451

## Pull request state

Please indicate actual status for PR:
- [x] on review
- [ ] reviewed
- [ ] fixed
- [ ] on approve
- [ ] approved

2021-01-01 20:03 UTC, Igrok023451 commented
Второй 6-ой это 7-мь.

2021-01-04 16:43 UTC, rakovets requested changes
How to work with Java APIs used in solutions?

Tests passed: 128/140.
Fix it.

2021-01-04 16:43 UTC, rakovets commented on src/main/java/com/rakovets/course/javabasics/practice/conditionalstatements/Task05.java
> +        }
What is it?

2021-01-04 16:43 UTC, rakovets commented on src/main/java/com/rakovets/course/javabasics/practice/conditionalstatements/Task09.java
> +         return (int)Math.ceil(apartmentNumber / (double)(numberFloors * numberApartmentsPerFloor));
What is it?

2021-01-04 16:43 UTC, rakovets commented on src/main/java/com/rakovets/course/javabasics/practice/conditionalstatements/Task11.java
> +        if(Pattern.matches("[a-zA-Z]",String.valueOf(symbol) )){
What is it?

2021-01-04 16:43 UTC, rakovets commented on src/main/java/com/rakovets/course/javabasics/practice/conditionalstatements/Task11.java
> +        if(Pattern.matches("[а-яА-Я]",String.valueOf(symbol) )){
What is it?

2021-01-04 16:43 UTC, rakovets commented on src/main/java/com/rakovets/course/javabasics/practice/conditionalstatements/Task11.java
> +        if(Pattern.matches("[0-9]",String.valueOf(symbol) )){
What is it?

2021-01-24 06:02 UTC, rakovets reviewed
Approved.

2021-01-24 06:03 UTC, closed without merging