Oop classes and objects / it-academy.by / M-JC1-66-20 / Oxana Peregud / Done Tasks 1-4
rakovets/course-java-core pull request #297
Opened 2021-01-15 20:51 UTC by OxanaPeregud

## Pull request state

Please indicate actual status for PR:
- [x] on review
- [ ] reviewed
- [ ] fixed
- [ ] on approve
- [ ] approved

2021-01-15 20:51 UTC, OxanaPeregud commented
Файлы с тестами не нужно проверять, я их для себя писала.

2021-01-20 17:25 UTC, rakovets requested changes
Good job but you need to fix following problem.

2021-01-20 17:25 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +    private int amount;
What is this?

2021-01-20 17:25 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +                for (int k = 0; k <= this.numberBanknotes20; k++) {
Wrong!
```suggestion
        for (int i = 0; i <= this.numberBanknotes20; i++) {
            for (int j = 0; j <= this.numberBanknotes50; j++) {
                for (int k = 0; k <= this.numberBanknotes100; k++) {
```

2021-01-20 17:25 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +                                optionsCombinationBanknotes += "20 x " + i + "   ";
Violation of Code Convention!
Use logical block `{}`

2021-01-20 17:25 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/AtmTest.java
> +
Where are tests for `add` methods?

2021-01-20 17:25 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Point.java
> +    private int y;
Why are you use `int`? Best `double`.

2021-01-20 17:25 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Time.java
> +    }
Why does specification contain 2 variables for one business value?
`seconds` != `totalSeconds`

2021-01-24 05:59 UTC, rakovets reviewed
Perfect job!

2021-01-24 05:59 UTC, closed without merging