Oop classes and objects / it-academy.by / M-JC1-66-20 / Yauhen Filipau / Done tasks 4/4
rakovets/course-java-core pull request #301
Opened 2021-01-18 14:27 UTC by FilippovZ

## Pull request state

Please indicate actual status for PR:
- [x] on review
- [ ] reviewed
- [ ] fixed
- [ ] on approve
- [ ] approved

2021-01-20 17:34 UTC, rakovets requested changes

2021-01-20 17:34 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +    }
What is this?

2021-01-20 17:34 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +    }
What is this?

2021-01-20 17:34 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +    private int amount;
What is this?

2021-01-20 17:34 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +    public void isPossibleIssue(int amount) {
Why doesn't it have return type?

2021-01-20 17:34 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +    public void getOptionsCombinationBanknotes(int amount) {
Why doesn't it have return type?

2021-01-20 17:34 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +    public void getCash(int option) {
Why doesn't it have return type?

2021-01-20 17:34 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Time.java
> +    }
Why does specification contain 2 variables for one business value?
`seconds` != `totalSeconds`

2021-01-20 17:35 UTC, rakovets commented
Good job but you need to fix following problem.

2021-01-20 17:55 UTC, FilippovZ commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +    }
Думал, что это конструктор для ввода суммы. Но уже понимаю, что он тут наверное не нужен.

2021-01-20 17:57 UTC, FilippovZ commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +    }
Это дефолтный конструктор. Думал, что его обязательно нужно создавать вручную если есть другие конструкторы. Но видимо не нужно.

2021-01-20 17:58 UTC, FilippovZ commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +    private int amount;
Это поля класса. А что тут не так?

2021-01-20 18:00 UTC, FilippovZ commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +    public void isPossibleIssue(int amount) {
Зачем return если я печатаю результат? В условии это явно не было написано что метод должен что-то возвращать.

2021-01-20 18:01 UTC, FilippovZ commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +    public void getOptionsCombinationBanknotes(int amount) {
Тоже самое, в условии не написано, что этот метод должен что-то возвращать.

2021-01-20 18:01 UTC, FilippovZ commented on src/main/java/com/rakovets/course/java/core/practice/oop/classesandobjects/Atm.java
> +    public void getCash(int option) {
аналогично

2021-01-30 05:29 UTC, rakovets approved these changes
Approved.

2021-01-30 05:29 UTC, closed without merging