date and time / it-academy.by / M-JC1-66-20 / Anastasia Gawriljuk / Done tasks 3/3
rakovets/course-java-core pull request #361
Opened 2021-02-15 11:58 UTC by Semargl92

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2021-02-15 18:57 UTC, rakovets approved these changes
Perfect job!

2021-02-15 18:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/date_and_time/date_wrapper/DateWrapper.java
> +            (temporal.get(ChronoField.DAY_OF_YEAR) >= 183)
What is 183?

2021-02-15 19:00 UTC, rakovets requested changes
Need to write test/demo for SPecification of tasks 2

2021-02-15 20:46 UTC, Semargl92 commented
> Need to write test/demo for SPecification of tasks 2

already have those tests, check, please: 
void getDateAfterDays
void adjustIntoClosestNewYear

2021-02-21 10:34 UTC, rakovets approved these changes
Approved.

2021-02-21 10:34 UTC, closed without merging