Concurrency thread synchronization / it-academy.by / M-JC1-66-20 / Yauhen Filipau / Done Producer-Consumer
rakovets/course-java-core pull request #394
Opened 2021-03-03 16:37 UTC by FilippovZ

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2021-03-04 23:40 UTC, FilippovZ commented
the project SkyNet was not fully completed, but due to the large amount of time spent, I would like to receive feedback.  Only 1 thread works in the method "getDetails", and the second Thread enters only after the first is fully completed, at the end. 
I don't know how to solve this problem

2021-03-08 18:40 UTC, rakovets requested changes
Good job but you must apply design principles.
You need to fix the following problems.

2021-03-08 18:40 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/thread_synchronization/skyNet/Details.java
> +public enum Details {
```suggestion
public enum Detail {
```

2021-03-08 18:40 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/thread_synchronization/skyNet/Storage.java
> +}
Violation SOLID

2021-03-11 15:26 UTC, closed without merging