operators/it-academy.by/M-JC1-69-21/Artem Shapel/Done tasks 4/6
rakovets/course-java-core pull request #426
Opened 2021-03-23 06:58 UTC by shapelartem

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2021-03-24 14:02 UTC, shapelartem commented
operators/it-academy.by/M-JC1-69-21/Artem Shapel/Done tasks 5/6

2021-03-25 13:29 UTC, rakovets requested changes
The following problems need to be fixed.
Need to add solution for task 6

2021-03-25 13:29 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/operators/Task01.java
> +        int numberFullTrucks = getNumberFullTrucks (cargo, carryingCapacity);
Why?

2021-03-25 13:29 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/operators/Task01.java
> +
Why?

2021-03-25 13:29 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/operators/Task01.java
> +    static int getNumberFullTrucks   (int cargo, int carryingCapacity)  {
Why?

2021-03-25 13:29 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/operators/Task03.java
> +         return y + depositAmount;
Bad name for variables

2021-03-25 13:29 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/operators/Task04.java
> +        return (SOUND_SPEED * milliseconds / 3600);
```suggestion
        return SOUND_SPEED * milliseconds / 3600;
```

2021-04-05 03:42 UTC, rakovets requested changes
You need to fix the following problems

2021-04-05 03:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/operators/Task03.java
> +        return percentTotal + depositAmount;
Invalid variable name because you cannot add a percentage to the amount. This is a wrong business transaction.

2021-04-15 04:00 UTC, closed without merging