Decision making statement/it-academy/M-JC1-69-21/andreidrozd/done tasks 1-10, 12-14
rakovets/course-java-core pull request #445
Opened 2021-03-29 06:13 UTC by andreidrozd

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2021-03-29 14:00 UTC, andreidrozd commented
solution: Done task13

2021-04-05 15:57 UTC, rakovets requested changes
You need to fix the following problems

2021-04-05 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statement/Task01.java
> +        return (sizeTop >= positionPlayerByDamage);
```suggestion
        return sizeTop >= positionPlayerByDamage;
```

2021-04-05 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statement/Task02.java
> +        }
This isn't effective.

2021-04-05 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statement/Task03.java
> +            }
This is difficult

2021-04-05 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statement/Task04.java
> +                return ("MONDAY");
```suggestion
                return "MONDAY";
```

2021-04-05 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statement/Task06.java
> +        }
Violation of DRY principle

2021-04-05 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statement/Task08.java
> +                    return damage;
```suggestion
                case "ANIMAL":
                case "HUMANOID":
                case "PLANT":
                case "GHOST":
                    return damage;
```

2021-04-05 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statement/Task10.java
> +        return 1;
This is difficult

2021-04-05 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statement/Task11.java
> +        if (Character.isDigit(symbol)) {
What is `Character`?

2021-04-05 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statement/Task12.java
> +        }    return null;
- This is difficult.
- Violations of Code Convention

2021-04-05 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statement/Task14.java
> +            if ((year % 12) == 0)
```suggestion
            if (year % 12 == 0)
```

2021-05-28 07:48 UTC, closed without merging