array / it-academy.by / M-JC1-69-21-8 / Igor Popov / Done tasks 1-3
rakovets/course-java-core pull request #478
Opened 2021-04-06 05:24 UTC by ipopov91

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2021-04-06 11:05 UTC, rakovets requested changes
You need to fix the following problems

2021-04-06 11:05 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/array/Task02.java
> +            for (int j = 0; j < marks[i].length; j++) {
Best way: using `foreach`

2021-04-06 11:05 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/array/Task03.java
> +            for (int j = 0; j < marks[0].length; j++) {
Best way: using `foreach`

2021-04-06 11:06 UTC, rakovets requested changes
You need to fix the following problems and add solution with completed tests

2021-04-20 05:41 UTC, ipopov91 commented on src/main/java/com/rakovets/course/java/core/practice/array/Task02.java
> +            for (int j = 0; j < marks[i].length; j++) {
done

2021-04-20 05:41 UTC, ipopov91 commented on src/main/java/com/rakovets/course/java/core/practice/array/Task03.java
> +            for (int j = 0; j < marks[0].length; j++) {
done

2021-04-20 05:41 UTC, ipopov91 commented on src/main/java/com/rakovets/course/java/core/practice/array/Task03.java
> +            for (int j = 0; j < marks[0].length; j++) {
done

2021-04-20 05:41 UTC, ipopov91 commented on src/main/java/com/rakovets/course/java/core/practice/array/Task03.java
> +            for (int j = 0; j < marks[0].length; j++) {
done

2021-04-26 13:22 UTC, rakovets approved these changes
Approved

2021-04-26 13:22 UTC, closed without merging