string / it-academy.by / M-JC1-69-21 / Evgeni Ermakov / Done tasks 19/19 String + 3 OptionalTask
rakovets/course-java-core pull request #495
Opened 2021-04-11 16:05 UTC by EvgeniErmakov

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2021-04-11 16:10 UTC, EvgeniErmakov reviewed
С выбором файлов на Pull requests еще поучусь.

2021-04-20 03:28 UTC, rakovets requested changes
You need to fix the following problems

2021-04-20 03:28 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +    public int PunctuationCounter(String text) {
```suggestion
    public int getPunctuationCount(String text) {
```

2021-04-20 03:28 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +    public boolean palindrome(String text) {
```suggestion
    public boolean isPalindrome(String text) {
```

2021-04-20 03:28 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +
Remove blank line

2021-04-20 03:28 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +
remove blank line

2021-05-24 08:05 UTC, rakovets approved these changes
Approved

2021-05-24 08:05 UTC, closed without merging