String / it-academy.by / M-JC1-69-21 / Bozhen Davydov / Done tasks 1 - 18
rakovets/course-java-core pull request #499
Opened 2021-04-12 10:10 UTC by davydovbv

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2021-04-20 03:50 UTC, rakovets requested changes
Please, fix all violations of the Code of the Convention.
After I will to do code review

2021-04-20 03:50 UTC, rakovets commented on build.gradle
> +    implementation 'org.jetbrains:annotations:20.1.0'
What is it???

2021-04-20 03:50 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +
Remove blank line

2021-04-20 03:50 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +    public  int  findIndexOfSymbol(char ch, String str) {
Violations of the Code of the Convention

2021-04-20 03:50 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +    public boolean correctBegin( String text, String word) {
Violations of the Code of the Convention

2021-04-20 03:50 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +        return  str1.replace(str2,str3);
Violations of the Code of the Convention

2021-04-20 03:50 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +
Violations of the Code of the Convention

2021-04-20 11:20 UTC, davydovbv commented on build.gradle
> +    implementation 'org.jetbrains:annotations:20.1.0'
Have no idea what is this)

2021-04-26 13:32 UTC, rakovets requested changes
You need to fix the following problems

2021-04-26 13:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2021-04-26 13:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2021-04-26 13:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +            if (count == 0){
"Violation: There isn't separating white spaces for curly brake
Solution: Add white spaces"

2021-04-26 13:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +        for(int i = 0; i < text.length() ; i += numberSymbols) {
```suggestion
        for(int i = 0; i < text.length(); i += numberSymbols) {
```

2021-04-26 13:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/string/StringUtil.java
> +            splitText = new String[text.length() / numberSymbols+1];
```suggestion
            splitText = new String[text.length() / numberSymbols + 1];
```

2021-05-25 12:37 UTC, closed without merging