Exception handling / it-academy.by / M-JC1-69-21 / Bozhen Davydov / Done tasks 1-7
rakovets/course-java-core pull request #529
Opened 2021-04-19 19:23 UTC by davydovbv

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2021-04-20 15:18 UTC, rakovets requested changes
You need to fix the following problems

2021-04-20 15:18 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/task_01/Task01.java
> +
Remove blank lines

2021-04-20 15:18 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/task_01_Test/Task01Demo.java
> +
Remove blank line

2021-04-20 15:18 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/task_03/Discount.java
> +        }
Contains violations of the Code of Convention

2021-04-20 15:18 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/task_05_Test/Task05Demo.java
> +
Contains violations of the Code of Convention

2021-04-20 15:18 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/task_06/Task06.java
> +}
This solution is wrong

2021-04-20 15:18 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/task_07/NumberChecker.java
> +        return number;
Contains violations of the Code of Convention

2021-04-22 09:20 UTC, rakovets requested changes
You need to fix the following problems and add a solution for other tasks

2021-04-22 09:20 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/task_03/Discount.java
> +            result = (int)(sum * 0.8);
```suggestion
        if (sum > 100) {
            result = (int) (sum * 0.8);
```

2021-04-22 09:20 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/task_07/NumberChecker.java
> +        if(number % 2 == 0) {
```suggestion
        if (number % 2 == 0) {
```

2021-04-22 09:20 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/task_01_Test/Task01Demo.java
> +        try{
```suggestion
        try {
```

2021-04-22 09:20 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/task_06/Task06.java
> +}
Where is solution correct?

2021-04-22 13:09 UTC, davydovbv commented
I hope I have fixed everything)

2021-04-26 13:44 UTC, rakovets approved these changes
Approved

2021-04-26 13:44 UTC, rakovets commented on build.gradle
> +    implementation 'org.testng:testng:7.1.0'
Don't touch configuration!!!

2021-04-26 13:44 UTC, closed without merging