Decision making statements / it-academy.by / JC1-110-22 / Alena Trafimovich / Done tasks 1-14
rakovets/course-java-core pull request #694
Opened 2022-06-09 06:58 UTC by AlenaTrafimovich

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-06-22 13:40 UTC, rakovets requested changes
Need to fix

2022-06-22 13:40 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task02.java
> +        return result;
this is hard

2022-06-22 13:40 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task07.java
> +        } else result = (year % 4 == 0);
bad practice

2022-06-22 13:40 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task08.java
> +
What is it?

2022-06-22 13:40 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task08.java
> +        return result;
use switch for it

2022-06-22 13:40 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task12.java
> +            result = null;
This is useless

2022-06-22 13:40 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task14.java
> +        return result;
this is hard

2022-06-23 08:05 UTC, rakovets approved these changes
Approved

2022-06-23 08:05 UTC, closed without merging

2022-06-23 08:17 UTC, AlenaTrafimovich commented
I wanted to add some more improvements, but it's closed already:))