feat: completed tasks 1-5
rakovets/course-java-core pull request #717
Opened 2022-06-13 06:17 UTC by DmitryVechorko

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-06-13 06:19 UTC, DmitryVechorko commented
feat: completed tasks 1-5

2022-06-23 08:09 UTC, rakovets requested changes
Need to fix and add another tasks

2022-06-23 08:09 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task01.java
> +        return topPlayer;
"Violation: There isn't separating white spaces (OR line break) for curly brake
Solution: Add white spaces"

2022-06-23 08:09 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task02.java
> +        return greeting;
"Violation: There isn't separating white spaces for operators OR parameters
Solution: Add white spaces"

2022-06-23 08:09 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task02.java
> +        return greeting;
"Code smell: Magic Number
Solution: Named Constants"

2022-06-23 08:09 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task03.java
> +        } else if (currentHealthLevel >=75 && currentHealthLevel <=100) {
"Violation: There isn't separating white spaces for operators OR parameters
Solution: Add white spaces"

2022-08-29 16:04 UTC, closed without merging