OOP Classes And Objects / it-academy.by / JC1-110-22 / Maksim Bondar / Tasks 1 - 4 complete
rakovets/course-java-core pull request #736
Opened 2022-06-19 16:27 UTC by shiv-qa-auto

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-06-20 14:45 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Time.java
> +    private int totalSeconds;
Remove filed which you can operate

2022-06-22 06:28 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Atm.java
> +
Fixed, plese review

2022-06-22 06:28 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Atm.java
> +
Fixed, plese review

2022-06-22 06:28 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Point.java
> +
Fixed, please review

2022-06-22 06:28 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Rectangle.java
> +    Point bottomRightPoint;
Fixed, please review

2022-06-22 06:28 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Rectangle.java
> +    public void setTopLeftPoint(int x, int y) {
Fixed, please review

2022-06-22 06:29 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Time.java
> +
Fixed, please review

2022-06-22 06:29 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Time.java
> +    private int totalSeconds;
Fixed, please review

2022-06-23 09:10 UTC, rakovets requested changes
Need to fix

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Atm.java
> +    public void addBanknotes20 (int x) {
"Violation: There isn't separating empty line
Solution: Add blank line"

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Atm.java
> +    public void addBanknotes50 (int x) {
"Violation: There isn't separating empty line
Solution: Add blank line"

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Atm.java
> +    public void addBanknotes100 (int x) {
"Violation: There isn't separating empty line
Solution: Add blank line"

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Atm.java
> +    public int getNumberBanknotes20() {
"Violation: There isn't separating empty line
Solution: Add blank line"

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Atm.java
> +    public int getNumberBanknotes50() {
"Violation: There isn't separating empty line
Solution: Add blank line"

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Atm.java
> +    public int getNumberBanknotes100() {
"Violation: There isn't separating empty line
Solution: Add blank line"

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Point.java
> +
```suggestion
package com.rakovets.course.java.core.practice.oop_classes_and_objects;

public class Point {
```

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Point.java
> +    public int getX() {
"Violation: There isn't separating empty line
Solution: Add blank line"

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Point.java
> +    public void setX(int x) {
"Violation: There isn't separating empty line
Solution: Add blank line"

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Point.java
> +    public int getY() {
"Violation: There isn't separating empty line
Solution: Add blank line"

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Point.java
> +    public double getDistance(Point p) {
"Violation: There isn't separating empty line
Solution: Add blank line"

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Rectangle.java
> +    private Point topLeftPoint;
```suggestion
package com.rakovets.course.java.core.practice.oop_classes_and_objects;

public class Rectangle {
    private Point topLeftPoint;
```

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Time.java
> +    public void setSeconds(int seconds) {
"Violation: There isn't separating empty line
Solution: Add blank line"

2022-06-23 09:10 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Time.java
> +    public int getTotalSeconds() {
"Violation: There isn't separating empty line
Solution: Add blank line"

2022-06-27 20:54 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Atm.java
> +    public void addBanknotes20 (int x) {
Fixed, please review

2022-06-27 20:55 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Atm.java
> +    public void addBanknotes100 (int x) {
Fixed, please review

2022-06-27 20:55 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Atm.java
> +    public int getNumberBanknotes20() {
Fixed, please review

2022-06-27 20:55 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Atm.java
> +    public int getNumberBanknotes50() {
Fixed, please review

2022-06-27 20:55 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Atm.java
> +    public int getNumberBanknotes100() {
Fixed, please review

2022-06-27 20:55 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Point.java
> +    public int getX() {
Fixed, please review

2022-06-27 20:55 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Point.java
> +    public int getY() {
Fixed, please review

2022-06-27 20:55 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Point.java
> +    public void setY(int y) {
Fixed, please review

2022-06-27 20:55 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Point.java
> +    public double getDistance(Point p) {
Fixed, please review

2022-06-27 20:56 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Rectangle.java
> +    private Point topLeftPoint;
Fixed, please review

2022-06-27 20:56 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Rectangle.java
> +    public void setTopLeftPoint(Point topLeftPoint) {
Fixed, please review

2022-06-27 20:56 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Rectangle.java
> +    public Point getBottomRightPoint() {
Fixed, please review

2022-06-27 20:56 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Rectangle.java
> +    public void setBottomRightPoint(Point bottomRightPoint) {
Fixed, please review

2022-06-27 20:56 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Rectangle.java
> +    public int getPerimeter() {
Fixed, please review

2022-06-27 20:56 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Time.java
> +    private int hours;
Fixed, please review

2022-06-27 20:57 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Time.java
> +    public int getHours() {
Fixed, please review

2022-06-27 20:57 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/oop_classes_and_objects/Time.java
> +    public void setSeconds(int seconds) {
Fixed, please review

2022-08-29 16:22 UTC, rakovets approved these changes

2022-08-29 16:22 UTC, closed without merging