Strings / it-academy.by / JC1-110-22 / Maksim Bondar / Tasks 1 - 14 complete
rakovets/course-java-core pull request #751
Opened 2022-06-26 18:58 UTC by shiv-qa-auto

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-06-27 15:01 UTC, rakovets requested changes
Need to fix

2022-06-27 15:01 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +        Assertions.assertEquals(actual, expected);
Use approach GIVEN empty line WHEN empty line THAN
```suggestion
        String expected = "789123";
        
        String actual = stringUtil.concatTwoStrings("789", "123");
        
        Assertions.assertEquals(actual, expected);
```

2022-06-28 18:54 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +    //Task 1
Fixed, please review

2022-06-28 18:54 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +    //Task 2
Fixed, please review

2022-06-28 18:54 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +        return index;
Fixed, please review

2022-06-28 18:54 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +    //Task 3
Fixed, please review

2022-06-28 18:54 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +    //Task 4
Fixed, please review

2022-06-28 18:54 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +    //Task 6
Fixed, please review

2022-06-28 18:54 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +    //Task 7
Fixed, please review

2022-06-28 18:54 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +    //Task 9
Fixed, please review

2022-06-28 18:55 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +    //Task 11
Fixed, please review

2022-06-28 18:55 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +    //Task 12
Fixed, please review

2022-06-28 18:55 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +    //Task 14
Fixed, please review

2022-06-28 18:55 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +
Fixed, please review

2022-06-28 18:55 UTC, shiv-qa-auto commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +    //Task 1 tests
Fixed, please review

2022-06-28 18:55 UTC, shiv-qa-auto commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +    //Task 4 tests
Fixed, please review

2022-06-28 18:56 UTC, shiv-qa-auto commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +    //Task 5 tests
Fixed, please review

2022-06-28 18:56 UTC, shiv-qa-auto commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +    //Task 6 tests
Fixed, please review

2022-06-28 18:56 UTC, shiv-qa-auto commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +    //Task 7 tests
Fixed, please review

2022-06-28 18:56 UTC, shiv-qa-auto commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +    //Task 8 tests
Fixed, please review

2022-06-28 18:56 UTC, shiv-qa-auto commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +    //Task 9 tests
Fixed, please review

2022-06-28 18:56 UTC, shiv-qa-auto commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +    //Task 10 tests
Fixed, please review

2022-06-28 18:56 UTC, shiv-qa-auto commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +    //Task 11 tests
Fixed, please review

2022-06-28 18:56 UTC, shiv-qa-auto commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +    //Task 12 tests
Fixed, please review

2022-06-28 18:56 UTC, shiv-qa-auto commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +    //Task 13 tests
Fixed, please review

2022-06-28 18:56 UTC, shiv-qa-auto commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +    //Task 14 tests
Fixed, please review

2022-06-28 18:56 UTC, shiv-qa-auto commented on src/test/java/com/rakovets/course/java/core/practice/strings/StringUtilTest.java
> +        Assertions.assertEquals(actual, expected);
Fixed, please review

2022-08-29 16:38 UTC, rakovets approved these changes

2022-08-29 16:38 UTC, closed without merging