Oop principles / it-academy.by / JC1-110-22 / Alena Trafimovich/ Done tasks 1-3
rakovets/course-java-core pull request #763
Opened 2022-07-02 11:57 UTC by AlenaTrafimovich

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-07-04 13:42 UTC, rakovets requested changes
Need to fix

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/CatHome/Siamese.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/CatHomeTest/CatTest.java
> +    private final Cat cat = new Cat("Cat");
move to `@BeforeAll`

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/BattleGround/Archer.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/BattleGround/TypeHero.java
> +}
remove it

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/BattleGround/TypeEnemy.java
> +}
remove it

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/BattleGround/Vampire.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/BattleGround/Warrior.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/BattleGround/Witch.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/BattleGround/Zombie.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Geometry/Circle.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Geometry/Diagonal.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Geometry/EquilateralTriangle.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Geometry/Figure.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Geometry/Foursquare.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Geometry/Height.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Geometry/ShapeUtils.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/BattleGroundTest/ArcherTest.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/BattleGroundTest/MagTest.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/BattleGroundTest/WitchTest.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/GeometryTest/EllipseTest.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/GeometryTest/EquilateralTriangleTest.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/GeometryTest/FoursquareTest.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/GeometryTest/RectangleTest.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/GeometryTest/ShapeUtilsTest.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/GeometryTest/TriangleTest.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/BattleGround/Mag.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 13:42 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/BattleGround/Mortal.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-08 16:15 UTC, AlenaTrafimovich commented
Corrected comments

2022-08-31 02:29 UTC, rakovets approved these changes

2022-08-31 02:29 UTC, closed without merging