oop_principles / it-academy.by / JC1-110-22 / Anastasia Melnikova/ Done tasks
rakovets/course-java-core pull request #764
Opened 2022-07-02 18:17 UTC by Stellmaria

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-07-04 14:13 UTC, rakovets requested changes
Need to fix

2022-07-04 14:13 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/progect/battle_ground/enemy/Vampire.java
> +    }
Remove it

2022-07-04 14:13 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/progect/battle_ground/enemy/Werewolf.java
> +    }
remove it

2022-07-04 14:13 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/progect/battle_ground/enemy/Zombie.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 14:13 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/progect/battle_ground/enemy/Zombie.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-04 14:13 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/progect/battle_ground/enemy/Zombie.java
> +    }
remove it

2022-07-04 14:13 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/progect/cats_home/Sphynx.java
> +        return "meow";
reuse method `mew()`

2022-07-04 14:13 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/progect/battle_ground/enemy/EnemyTest.java
> +    };
move to @BeforeAll

2022-07-04 14:13 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/progect/battle_ground/enemy/ZombieResurrectionTest.java
> +public class ZombieResurrectionTest {
```suggestion
public class ZombieResurrectionDemo {
```

2022-07-04 14:22 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/progect/battle_ground/enemy/Zombie.java
> +
fixed

2022-07-04 14:22 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/progect/battle_ground/enemy/Zombie.java
> +
fixed

2022-07-04 14:27 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/progect/cats_home/Sphynx.java
> +        return "meow";
fixed

2022-07-04 20:03 UTC, Stellmaria commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/progect/battle_ground/enemy/EnemyTest.java
> +    };
fixed

2022-07-06 14:28 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/progect/battle_ground/enemy/Zombie.java
> +    }
fixed

2022-08-31 02:34 UTC, closed without merging