exception handling / it-academy / JC1-110-22 / Evgeniy Antonovich / Done tasks 1- 7
rakovets/course-java-core pull request #779
Opened 2022-07-09 08:11 UTC by aevgeni

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-07-11 12:32 UTC, rakovets requested changes
Need to fix

2022-07-11 12:32 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task1Demo.java
> +        } catch (Exception e) {
Best practice: catch a specific exception

2022-07-11 12:32 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/exception_handling/Task1Demo.java
> +            e.printStackTrace();
please add one sout

2022-07-11 12:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task6.java
> +    public void getOneOfThreeExceptions(int variant) throws ArithmeticException, ArrayIndexOutOfBoundsException, NullPointerException {
Violation for Specification of Tasks

2022-07-11 12:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task7.java
> +    public void getException(int variant) throws SocketException {
Violation for Specification of Tasks

2022-07-17 13:56 UTC, aevgeni commented
Fixed all violation

2022-08-26 06:46 UTC, aevgeni commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task6.java
> +    public void getOneOfThreeExceptions(int variant) throws ArithmeticException, ArrayIndexOutOfBoundsException, NullPointerException {
fixed it

2022-08-26 06:46 UTC, aevgeni commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task7.java
> +    public void getException(int variant) throws SocketException {
fixed it

2022-08-31 02:59 UTC, rakovets approved these changes

2022-08-31 02:59 UTC, closed without merging