Exception handling / it-academy.by / JC1-110-22 / Maksim Bondar / Tasks 1 - 7 complete
rakovets/course-java-core pull request #785
Opened 2022-07-10 19:22 UTC by shiv-qa-auto

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-07-11 12:58 UTC, rakovets requested changes
Need full refactoring:

Task - throw exception
Demo - catch exception

2022-07-11 12:58 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task4.java
> +
"Violation: Useless blank lines
Solution: Remove blank lines"

2022-07-18 20:12 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task1.java
> +
Fixed, please review

2022-07-18 20:12 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task2.java
> +
Fixed, please review

2022-07-18 20:12 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task3.java
> +
Fixed, please review

2022-07-18 20:13 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/exception_handling/Task5.java
> +
Fixed, please review

2022-08-31 03:02 UTC, rakovets approved these changes

2022-08-31 03:02 UTC, closed without merging