Jcf collection / it-academy.by / JC1-110-22 / Alena Trafimovich / Done tasks 1-2
rakovets/course-java-core pull request #791
Opened 2022-07-17 13:26 UTC by AlenaTrafimovich

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-07-25 13:57 UTC, rakovets requested changes
need to fix

2022-07-25 13:57 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/jcf_collection/StringCollectionUtilTest.java
> +    }
fix

2022-07-25 13:57 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/jcf_collection/StringCollectionUtilTest.java
> +    }
fix

2022-07-26 12:22 UTC, AlenaTrafimovich commented
I have fixed comments

2022-08-31 03:29 UTC, closed without merging