Jcf collection / it-academy.by /  JC1-110-22 / Alena Trafimovich / Done tasks 1-2
rakovets/course-java-core pull request #792
Opened 2022-07-17 13:30 UTC by AlenaTrafimovich

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-07-25 14:07 UTC, rakovets requested changes
Need to fix

2022-07-25 14:07 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/SchoolClass.java
> +    };
move to separate classes

2022-07-25 14:07 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/Studio.java
> +    };
move to separate classes

2022-07-25 14:07 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/jcf_list/SchoolClassTest.java
> +    private final List<Person> list = new ArrayList<>(Arrays.asList(person1, person2, person3, person4));
move to init method

2022-07-25 14:07 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/jcf_list/SchoolClassTest.java
> +    }
fix

2022-07-25 14:07 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/jcf_list/StudioTest.java
> +    }
fix

2022-07-26 13:01 UTC, AlenaTrafimovich commented
I've fixed comments

2022-08-31 03:29 UTC, closed without merging