Jcf collection, list / it-academy / JC1-110-22 / Evgeniy Antonovich / Done tasks collections and List
rakovets/course-java-core pull request #800
Opened 2022-07-19 13:38 UTC by aevgeni

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-07-25 14:31 UTC, rakovets requested changes

2022-07-25 14:31 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_collection/StringCollectionUtil.java
> +    }
fix

2022-07-25 14:31 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/class_/Person.java
> +    }
move to bottom

2022-07-25 14:31 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/studio/Actor.java
> +    }
move to bottom

2022-07-25 14:31 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/jcf_collection/StringCollectionUtilDemo.java
> +public class StringCollectionUtilDemo {
Best way: tests

2022-07-25 14:31 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/jcf_list/class_/ClassDemo.java
> +public class ClassDemo {
Best way: tests

2022-07-25 14:31 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/jcf_list/studio/StudioDemo.java
> +public class StudioDemo {
Best way: tests

2022-08-26 07:05 UTC, aevgeni commented on src/main/java/com/rakovets/course/java/core/practice/jcf_collection/StringCollectionUtil.java
> +    }
fixed it

2022-08-26 07:05 UTC, aevgeni commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/class_/Person.java
> +    }
did it

2022-08-26 07:06 UTC, aevgeni commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/studio/Actor.java
> +    }
did it

2022-08-26 07:06 UTC, aevgeni commented on src/test/java/com/rakovets/course/java/core/practice/jcf_list/class_/ClassDemo.java
> +public class ClassDemo {
got it

2022-08-26 07:06 UTC, aevgeni commented on src/test/java/com/rakovets/course/java/core/practice/jcf_list/studio/StudioDemo.java
> +public class StudioDemo {
got it

2022-08-31 03:32 UTC, closed without merging