jcf_list/ it-academy.by/ JC1-110-22 / Melnikova Anastasia/ Done project String collection util
rakovets/course-java-core pull request #804
Opened 2022-07-20 10:36 UTC by Stellmaria

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-07-25 15:04 UTC, rakovets requested changes
need to fix

2022-07-25 15:04 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/clazz/Person.java
> +    }
move to bottom

2022-07-25 15:04 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/clazz/SchoolClass.java
> +
remove it

2022-07-25 15:04 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/clazz/SchoolClass.java
> +
remove it

2022-07-25 15:04 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/clazz/SchoolClass.java
> +
remove it

2022-07-25 15:04 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/jcf_collection/StringCollectionUtilTest.java
> +    }
fix it

2022-07-25 15:04 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/jcf_list/StudioTest.java
> +
remove it

2022-07-26 10:32 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/jcf_collection/StringCollectionUtil.java
> +    static Collection<String> resetWordsByLength(Collection<String> collection, int size) {
fixed

2022-07-26 10:32 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/jcf_collection/StringCollectionUtil.java
> +    static Collection<String> resetWordsByLength(Collection<String> collection, int size) {
fixed

2022-07-26 10:33 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/jcf_collection/StringCollectionUtil.java
> +    static void removeWordsByLength(Collection<String> collection, int size) {
fixed

2022-07-26 10:33 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/clazz/Person.java
> +     */
fixed

2022-07-26 10:33 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/clazz/Person.java
> +    }
fixed

2022-07-26 10:33 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/clazz/SchoolClass.java
> +
fixed

2022-07-26 10:33 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/clazz/SchoolClass.java
> +
fixed

2022-07-26 10:33 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/jcf_list/clazz/SchoolClass.java
> +
fixed

2022-07-26 10:34 UTC, Stellmaria commented on src/test/java/com/rakovets/course/java/core/practice/jcf_collection/StringCollectionUtilTest.java
> +    }
fixed

2022-07-26 10:34 UTC, Stellmaria commented on src/test/java/com/rakovets/course/java/core/practice/jcf_list/StudioTest.java
> +
fixed

2022-08-31 03:34 UTC, closed without merging