Jcf map, set / it-academy / JC1-110-22 / Evgeniy Antonovich / Done tasks Map and Set
rakovets/course-java-core pull request #806
Opened 2022-07-24 11:50 UTC by aevgeni

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-07-26 03:57 UTC, rakovets requested changes
Need to fix

2022-07-26 03:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_set/Citizen.java
> +    private final int id;
fix
```suggestion
    private final int id;
    private final int yearOfBirth;
    private String firstName;
    private String lastName;
    private String locationCity;
```

2022-07-26 03:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_set/Fine.java
> +    private final int fineId;
fix
```suggestion
    private final int citizenId;
    private final int fineId;
    private double articleNumber;
    private String description;
    private double fineAmount;
    private boolean isPaid;
```

2022-07-26 03:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_set/TaxService.java
> +        return null;
throw Exception

2022-07-26 03:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_set/TaxService.java
> +        return null;
throw Exception

2022-07-26 03:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_set/TaxService.java
> +    }
Case: `fineId` don't exists

2022-07-26 03:57 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/jcf_set/TaxServiceDemo.java
> +import java.util.*;
Don't use * import

2022-08-26 08:03 UTC, aevgeni commented on src/main/java/com/rakovets/course/java/core/practice/jcf_set/TaxService.java
> +        return null;
did it

2022-08-26 08:03 UTC, aevgeni commented on src/main/java/com/rakovets/course/java/core/practice/jcf_set/TaxService.java
> +        return null;
did it

2022-08-26 08:04 UTC, aevgeni commented on src/main/java/com/rakovets/course/java/core/practice/jcf_set/TaxService.java
> +    }
added "throw Exception"

2022-08-26 08:04 UTC, aevgeni commented on src/test/java/com/rakovets/course/java/core/practice/jcf_set/TaxServiceDemo.java
> +import java.util.*;
fixed it

2022-08-31 03:37 UTC, closed without merging