jfc-map / it-academy.by / JC1-110-22 / Maksim Bondar / task 'Words monitoring' complete
rakovets/course-java-core pull request #809
Opened 2022-07-25 09:59 UTC by shiv-qa-auto

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-07-26 04:13 UTC, rakovets requested changes
Need to add theme 'Set'

2022-07-26 04:13 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/jcf_map/TextMonitoring.java
> +import java.util.*;
Don't use * import

2022-07-26 04:13 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/jcf_map/TextMonitoringDemo.java
> +public class TextMonitoringDemo {
Best way: tests

2022-07-27 05:45 UTC, shiv-qa-auto commented on src/main/java/com/rakovets/course/java/core/practice/jcf_map/TextMonitoring.java
> +import java.util.*;
Fixed

2022-08-31 03:39 UTC, closed without merging