Lambda expressions / it-academy.by / JC1-110-22 / Alena Trafimovich / Done tasks
rakovets/course-java-core pull request #814
Opened 2022-07-31 13:00 UTC by AlenaTrafimovich

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-08-01 15:22 UTC, rakovets requested changes
Need to fix

2022-08-01 15:22 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/ArgumentValueHelper.java
> +
Remove blank line

2022-08-01 15:22 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/ArgumentValueHelper.java
> +        return list.toArray(new String[0]);
Use Stream API

2022-08-01 15:22 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/ArgumentValueHelperTest.java
> +    private String[] text;
move to local var

2022-08-01 15:22 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/ArgumentValueHelperTest.java
> +    private final ArgumentValueHelper argumentValueHelper = new ArgumentValueHelper();
move to `@BeforeEach`

2022-08-01 15:22 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/CityHelper.java
> +
move blank line

2022-08-01 15:22 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/MultiplicationTable.java
> +
move blank line

2022-08-01 15:22 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/CityHelper.java
> +    }
this is dirty hack

2022-08-01 15:22 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/MathStatisticsTest.java
> +    }
What is it?

2022-08-01 15:22 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/TvSeller.java
> +
remove blank line

2022-08-01 15:22 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/TvSeller.java
> +        }
use ternary operator

2022-08-01 15:22 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/TvSeller.java
> +        }
use ternary operator

2022-08-08 11:36 UTC, AlenaTrafimovich commented
Fixed

2022-08-31 03:48 UTC, closed without merging