Lambda expressions / it-academy / JC1-110-22 / Evgeniy Antonovich / Done tasks
rakovets/course-java-core pull request #816
Opened 2022-08-01 11:10 UTC by aevgeni

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-08-01 15:57 UTC, rakovets requested changes
Need to fix

2022-08-01 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/MathStatistics.java
> +                .boxed().collect(Collectors.toList());
```suggestion
        return new Random().ints(amount, from, to)
                    .boxed()
                    .collect(Collectors.toList());
```

2022-08-01 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/MathStatistics.java
> +        return (int) collection.stream().filter(x -> x % 2 == 0).count();
```suggestion
        return collection.stream()
                .filter(x -> x % 2 == 0)
                .count();
```

2022-08-01 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/MathStatistics.java
> +    public int countEvenNumbers(Collection<Integer> collection) {
```suggestion
    public long countEvenNumbers(Collection<Integer> collection) {
```

2022-08-01 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/CityHelper.java
> +        return collection.stream().distinct().collect(Collectors.toList());
```suggestion
        return collection.stream()
                .distinct()
                .collect(Collectors.toList());
```

2022-08-01 15:57 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/CityHelperTest.java
> +class CityHelperTest {
```suggestion
public class CityHelperTest {
```

2022-08-01 15:57 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/CityHelperTest.java
> +    CityHelper cityHelper = new CityHelper();
```suggestion
    private CityHelper cityHelper;
    
    @BeforeEach
    voide initEach() {
         cityHelper = new CityHelper()
    }
```

2022-08-01 15:57 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/CityHelperTest.java
> +
```suggestion
    List<String> cities = List.of("Minsk", "Minsk", "Grodno", "Grodno", "Gomel", "Vitebsk", "Mogilev", "Brest");

```

2022-08-01 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/tv/TvUtil.java
> +public class TvUtil {
```suggestion
public class TvStore {
```

2022-08-01 15:57 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/tv/TvUtil.java
> +    Collection<Tv> tvCollection;
```suggestion
    private Collection<Tv> tvCollection;
```

2022-08-26 08:23 UTC, aevgeni commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/MathStatistics.java
> +        return (int) collection.stream().filter(x -> x % 2 == 0).count();
fixed it

2022-08-26 08:23 UTC, aevgeni commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/MathStatistics.java
> +    public int countEvenNumbers(Collection<Integer> collection) {
fixed it

2022-08-26 08:24 UTC, aevgeni commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/CityHelperTest.java
> +class CityHelperTest {
fixed it

2022-08-26 08:24 UTC, aevgeni commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/CityHelperTest.java
> +    CityHelper cityHelper = new CityHelper();
fixed it

2022-08-26 08:24 UTC, aevgeni commented on src/test/java/com/rakovets/course/java/core/practice/lambda_expressions/CityHelperTest.java
> +
fixed it

2022-08-26 08:24 UTC, aevgeni commented on src/main/java/com/rakovets/course/java/core/practice/lambda_expressions/tv/TvUtil.java
> +public class TvUtil {
fixed it

2022-08-31 03:48 UTC, closed without merging