Concurrency / it-academy.by / JC1-110-22 / Anastasia Melnikova / Done tasks 1-8
rakovets/course-java-core pull request #830
Opened 2022-08-07 17:32 UTC by Stellmaria

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-08-08 14:43 UTC, rakovets requested changes
Need to fix

2022-08-08 14:43 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/concurrency/ProducerDemo.java
> +        Queue<Integer> queue = new LinkedBlockingQueue<>();
Dirty hack

2022-08-08 14:43 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/Consumer.java
> +        } catch (NullPointerException exception) {
Bad practice

2022-08-08 14:43 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/Consumer.java
> +                new FileOutputStream(Path.of("resources", "text", "test.txt").toFile()))) {
Best practice: getting filename from CLI arguments

2022-08-08 14:43 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/Producer.java
> +                    throw new UserInputException("Incorrect input");
bad practice

2022-08-15 09:10 UTC, Stellmaria commented on src/test/java/com/rakovets/course/java/core/practice/concurrency/ProducerDemo.java
> +        Queue<Integer> queue = new LinkedBlockingQueue<>();
fixed

2022-08-15 09:10 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/Consumer.java
> +        } catch (NullPointerException exception) {
fixed

2022-08-15 09:10 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/Consumer.java
> +                new FileOutputStream(Path.of("resources", "text", "test.txt").toFile()))) {
fixed

2022-08-15 09:28 UTC, Stellmaria commented on src/main/java/com/rakovets/course/java/core/practice/concurrency/Producer.java
> +                    throw new UserInputException("Incorrect input");
fixed

2022-08-31 04:02 UTC, closed without merging