decision making statements / it-academy / JC1-117-22 / Dzmitry Krasiuk / Done all tasks
rakovets/course-java-core pull request #874
Opened 2022-09-14 18:17 UTC by Dzmitry-Highlander

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-09-19 11:26 UTC, rakovets requested changes
Need to fix

2022-09-19 11:26 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task07.java
> +        return isYearLeap;
WRONG

2022-09-19 11:26 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task04.java
> +                dayOfTheWeek = "THURSDAY";
WRONG

2022-09-19 11:26 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task10.java
> +        return firstToFuel;
WRONG

2022-09-19 11:26 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task11.java
> +        if ((int) symbol >= 65529 && (int) symbol <= 65333) {
"Code smell: Magic Number
Solution: Named Constants"

2022-09-19 11:26 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task11.java
> +        } else if ((int) symbol >= 65 && (int) symbol <= 90 || (int) symbol >= 97 && (int) symbol <= 122) {
"Code smell: Magic Number
Solution: Named Constants"

2022-09-19 11:26 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task11.java
> +        } else if ((int) symbol >= 1024 && (int) symbol <= 1273) {
"Code smell: Magic Number
Solution: Named Constants"

2022-09-19 11:26 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task11.java
> +        } else if ((int) symbol >= 48 && (int) symbol <= 57) {
"Code smell: Magic Number
Solution: Named Constants"

2022-09-19 11:26 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task13.java
> +        }
Need to add solution with `if`

2022-09-19 11:26 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task14.java
> +        }
Best way: use `%` operator

2022-09-19 13:58 UTC, Dzmitry-Highlander commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task08.java
> +        if (hasHolyAttribute) {
done

2022-09-26 04:45 UTC, rakovets approved these changes

2022-09-26 04:45 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task02.java
> +        int sunset = 18;
use CONSTANTS

2022-09-26 04:45 UTC, closed without merging