decision_making_statetments / it-academy / JC1-117-22 / Victor Polonnikov / tasks 01-14
rakovets/course-java-core pull request #895
Opened 2022-09-18 13:53 UTC by VictPol

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-09-19 13:09 UTC, rakovets requested changes
Need to fix

2022-09-19 13:09 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task14.java
> +                break;
DRY

2022-09-25 18:58 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task01.java
> +        } else return false;
fixed to easier

2022-09-25 18:59 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task02.java
> +        } else if (hour >= 12 && hour <= 17) {
fixed with Magic Number Solution: named Consnants

2022-09-25 18:59 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task02.java
> +        if (hour >= 6 && hour <=11) {
fixed with Magic Number Solution: named Consnants

2022-09-25 19:00 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task02.java
> +        } else if (hour >= 18 && hour <= 23) {
fixed with Magic Number Solution: named Consnants

2022-09-25 19:00 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task02.java
> +        } else if (hour >= 0 && hour <= 5 || hour == 24) {
fixed with Magic Number Solution: named Consnants

2022-09-25 19:01 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task03.java
> +            return "GREEN";
fixed, no more repeat yourself in code

2022-09-25 19:02 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task06.java
> +            return "Player 1: " + tanksKilledFirstPlayer * KILL_POINT + ". Player 2: " + (tanksKilledSecondPlayer * KILL_POINT + BONUS_POINT);
fixed, no more repeat yourself in code

2022-09-25 19:02 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task08.java
> +        int _totalDamage;
fixed, variable renamed

2022-09-25 19:03 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task11.java
> +        String _symbolType = "undefined";
fixed, variable rename

2022-09-25 19:03 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task11.java
> +        if (48 <= codeDecimal && codeDecimal <= 57) {
fixed with Magic Number Solution: named Consnants

2022-09-25 19:04 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task11.java
> +        } else if ((65 <= codeDecimal && codeDecimal <= 90) || (97 <= codeDecimal && codeDecimal <= 122)) {
fixed with Magic Number Solution: named Consnants

2022-09-25 19:04 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task11.java
> +        } else if (1040 <= codeDecimal && codeDecimal <= 1103) {
fixed with Magic Number Solution: named Consnants

2022-09-25 19:07 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task12.java
> +        return _zodiacSign;
fixed partly. Variable renamed. Kindly ask let me keep this code, I like this unstandart solution.

2022-09-25 19:08 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task13.java
> +        int _floorNumber = 0;
fixed, variable rename

2022-09-25 19:09 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task14.java
> +                break;
fixed, no more repeat myself in code

2022-09-25 19:10 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task10.java
> +        int _numberStation;
fixed, variable rename

2022-09-26 05:16 UTC, rakovets approved these changes

2022-09-26 05:16 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task02.java
> +        final int midnightHour = 24;
use CONSTANTS

2022-09-26 05:16 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task06.java
> +        }
not readable

2022-09-26 05:16 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task08.java
> +                case "GHOST":
this `default`

2022-09-26 05:16 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task12.java
> +        }
hard

2022-09-26 05:16 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/decision_making_statements/Task14.java
> +                zodiacYearName = "Dragon";
DRY
hard

2022-09-26 05:16 UTC, closed without merging