add lesson04 Task01-10
rakovets/course-java-core pull request #900
Opened 2022-09-18 20:10 UTC by haretski-aliaksei

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-10-06 03:30 UTC, rakovets requested changes
Need to add correct solution

2022-10-06 03:30 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/looping_statements/Task09.java
> +        }
hard

2022-10-06 03:30 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/looping_statements/Task10.java
> +        }
wrong solution

2022-10-18 17:29 UTC, haretski-aliaksei commented
Fixed PR: https://github.com/rakovets/course-java-core/pull/975

2023-02-19 09:45 UTC, closed without merging