strings / it-academy.by / JC1-117-22 / Aliaksei Kharko / Done tasks 01-03, StringUtil and StringUtilTest
rakovets/course-java-core pull request #962
Opened 2022-10-02 21:30 UTC by KharkoAO

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-10-05 04:03 UTC, rakovets requested changes
You need to fix and add solution for task 11

2022-10-05 04:03 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +            }
```suggestion
            if (words[i] != " ") {
                count++;
            }
```

2022-10-05 11:31 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +    public String splitLine(String str, int n) {
This fixed

2022-10-05 11:31 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +        }
This fixed

2022-10-05 11:31 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +            }
This fixed

2022-10-06 04:38 UTC, rakovets requested changes
Need to fix

2022-10-06 04:38 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/strings/StringUtil.java
> +    public String splitStringApartOnNumberCharacters(String str, int n) {
method MUST return ARRAY

2023-01-18 13:58 UTC, rakovets commented
outdated

2023-01-18 13:58 UTC, closed without merging