oop-principles / it-academy / JC1-117-22 / Ekaterina Komleva / Done all tasks
rakovets/course-java-core pull request #981
Opened 2022-10-08 19:30 UTC by KateKoml

## Pull request state

Actual status for PR:
- [x] implemented
- [x] reviewed
- [x] fixed
- [ ] approved

2022-10-11 03:32 UTC, rakovets requested changes
You need to fix

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/cat/cats/Cat.java
> +        double percentHappiness = -5;
move to class's constant

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/cat/cats/Cat.java
> +
```suggestion

```

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/cat/cats/Cat.java
> +
```suggestion
```

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/cat/cats/Persian.java
> +
```suggestion
```

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/cat/cats/Persian.java
> +        double percentHappiness = -7;
etc

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/cat/cats/Siamese.java
> +
```suggestion
```

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/cat/cats/Sphynx.java
> +
```suggestion
```

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/cat/cats/Sphynx.java
> +        double percentHappiness = -25;
etc

2022-10-11 03:32 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/CatTests.java
> +
```suggestion
```

2022-10-11 03:32 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/CatTests.java
> +    }
use Parametrized tests

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_ground/heroes/Hero.java
> +    public abstract boolean isAlive();
You need to add impl

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_ground/enemies/Enemy.java
> +
```suggestion
```

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_ground/enemies/Enemy.java
> +    public abstract boolean isAlive();
add impl

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_ground/heroes/Mag.java
> +    public Mag(String name) {
```suggestion
    private double mana;
    
    public Mag(String name) {
```

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_ground/heroes/Warrior.java
> +    public Warrior(String name) {
```suggestion
    private double armor;
    
    public Warrior(String name) {
```

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_ground/heroes/Archer.java
> +    public Archer(String name) {
```suggestion
    private int fireArrowsNumber;
    
    public Archer(String name) {
```

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_ground/enemies/Demon.java
> +    public Demon(double health) {
```suggestion
    private int chanceToUseSuperAttack;
    
    public Demon(double health) {
```

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_ground/enemies/Werewolf.java
> +    public boolean isAlive() {
use override

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_ground/enemies/Zombie.java
> +    public Zombie(double health) {
```suggestion
    private int chanceToBeAlive;
    
    public Zombie(double health) {
```

2022-10-11 03:32 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_ground/enemies/Zombie.java
> +public class Zombie extends Enemy{
```suggestion
public class Zombie extends Enemy {
```

2022-10-11 03:32 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/BattleGroundTest.java
> +    public static void main(String[] args) {
move to `Demo`

2022-10-13 05:42 UTC, KateKoml commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/CatTests.java
> +                Arguments.of(new Person(50.0), new Cat("Bob"), 45.0),
```suggestion
                Arguments.of(new Person(50.0), new Cat("Bob"), 46.0),
```

2023-01-25 14:33 UTC, closed without merging