oop_principles / it-academy.by / JC1-117-22 / Aliaksei Kharko / Done tasks and tests for Project: 'Cat's Home' and 'Battle Ground'
rakovets/course-java-core pull request #990
Opened 2022-10-09 17:04 UTC by KharkoAO

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-10-11 04:26 UTC, rakovets requested changes
You need fix and rewrite all tests

2022-10-11 04:26 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/cats_home/Cat.java
> +class Cat {
```suggestion
public class Cat {
```

2022-10-11 04:26 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/cats_home/CatsTest.java
> +    void testSetAndGetNameMewAndPurrMethods(String name, String expected) {
separate tests

2022-10-11 04:26 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/cats_home/PersianTest.java
> +public class PersianTest {
use one test's class for Cats

2022-10-11 04:26 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_groud/Enemy.java
> +        return attackHero(hero);
What is it?

2022-10-11 04:26 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_groud/Archer.java
> +        System.out.println("Archer attacks!");
remove it from prod code

2022-10-11 06:15 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/cats_home/Cat.java
> +class Cat {
This fixed

2022-10-11 06:19 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_groud/Archer.java
> +        System.out.println("Archer attacks!");
This fixed

2022-10-11 06:24 UTC, KharkoAO commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/battle_groud/Enemy.java
> +        return attackHero(hero);
This fixed

2022-10-11 08:57 UTC, KharkoAO commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/cats_home/CatsTest.java
> +    void testSetAndGetNameMewAndPurrMethods(String name, String expected) {
This fixed

2022-10-11 08:57 UTC, KharkoAO commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/cats_home/PersianTest.java
> +public class PersianTest {
This fixed

2023-01-25 14:32 UTC, rakovets commented
outdated

2023-01-25 14:32 UTC, closed without merging