OOP Principles / it-academy / JC1-117-22 / Victor Polonnikov / Done Tasks 1-2
rakovets/course-java-core pull request #999
Opened 2022-10-10 01:16 UTC by VictPol

## Pull request state

Actual status for PR:
- [x] implemented
- [ ] reviewed
- [ ] fixed
- [ ] approved

2022-10-12 04:34 UTC, rakovets requested changes
You need to fix and add correct solution

2022-10-12 04:34 UTC, rakovets commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Warrior.java
> +    Warrior (String name) {
```suggestion
public class Warrior extends Hero {
    public Warrior (String name) {
```

2022-10-12 04:34 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/ArcherTests.java
> +    }
it isn't test

2022-10-12 04:34 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/ArcherTests.java
> +}
```suggestion
    }
}
```

2022-10-12 04:34 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/CatTests.java
> +    }
it isn't

2022-10-12 04:34 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/HeroTests.java
> +}*/
remove unused code

2022-10-12 04:34 UTC, rakovets commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/MagTests.java
> +    public void testMag(){
```suggestion
    public void testMag() {
```

2022-10-13 10:00 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Archer.java
> +        System.out.println("Archer attacks enemy");
This method can`t be rmoved, it is declared as abstract method in syperclass Hero according tj the specification and must be overrided in subclass Archer

2022-10-13 10:11 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Cat.java
> +    public void mew() { System.out.println("mjau"); }
fixed

2022-10-13 10:12 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Cat.java
> +    public void purr() {
fixed

2022-10-13 10:12 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Cat.java
> +        person.changeHappiness(-1);
fixed

2022-10-13 10:13 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Enemy.java
> +    Enemy(int health) {
fixed

2022-10-13 10:17 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Hero.java
> +    }
fixed

2022-10-13 10:19 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Hero.java
> +    public void setHealth(int health) {
fixed

2022-10-13 10:21 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Hero.java
> +    public int getHealth(){
fixed

2022-10-13 10:21 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Hero.java
> +    public void takeDamage(int damage) {
fixed

2022-10-13 10:23 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Mag.java
> +        System.out.println("Mag attacks enemy");
This method can`t be rmoved, it is declared as abstract method in syperclass Hero according to the specification and must be overrided in subclass Mag

2022-10-13 10:23 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Persian.java
> +    Persian(String name) {
fixed

2022-10-13 10:30 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Persian.java
> +        System.out.println("murrPersian");
fixed

2022-10-13 10:35 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Person.java
> +    Person(double happiness) {
fixed

2022-10-13 10:35 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Person.java
> +    final int HUNDRED_PERCENTS = 100;
fixed

2022-10-13 10:36 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Warrior.java
> +    Warrior (String name) {
fixed

2022-10-13 10:37 UTC, VictPol commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/ArcherTests.java
> +}
fixed

2022-10-13 10:39 UTC, VictPol commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/HeroTests.java
> +}*/
fixed

2022-10-13 10:40 UTC, VictPol commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/MagTests.java
> +    public void testMag(){
fixed

2022-10-13 10:43 UTC, VictPol commented on src/main/java/com/rakovets/course/java/core/practice/oop_principles/Persian.java
> +        System.out.println("mjauPersian");
fixed

2022-10-13 10:54 UTC, VictPol commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/ArcherTests.java
> +    }
fixed

2022-10-13 11:18 UTC, VictPol commented on src/test/java/com/rakovets/course/java/core/practice/oop_principles/CatTests.java
> +    }
fixed

2023-01-25 14:31 UTC, rakovets commented
outdated

2023-01-25 14:31 UTC, closed without merging